### ISSUE TITLE
Important: Method chaining not complex enough for an A+

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group24#22]
Hello,

@sairafurqan and I are going through your project and you have met all but two of the criteria for an A+. One of the things is really easy, and the other one is slightly more involved.

Here are the two things missing:

- [x] Issues aren't closed (though all the tasks are completed) ; effective use of issues requires all resolved issues to be closed.
Here are the two things missing:

- [x] Upon closer look, we haven't seen evidence of the "complex method chaining" criteria for `analysis1` and `analysis3`

>  Complex method chaining
> - At least three advanced operations (for e.g anonymous or lambda functions in assign or apply functions)
> - At least two method chains

At the moment, we're leaning towards downgrading your project to an A, but if you can fix these things before April 24th, we can award you your contracted grade of an A+.

Of course, you are more than welcome to just accept the A, but please let us know either way what you decide.

Thanks,

Dr. Moosvi

**Comment by MithishR** [comment]
Hi Professor, I have added more complex method chains in `analysis1`

**Comment by RajveerSodhi** [comment]
Previous issues closed.

**Comment by KYash03** [comment]
Done
